version: "3.9" 

services:

  dev: 
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
      PORT: 5173
    ports:
      - 5173:5173
    volumes:
      - ./public:/app/public
      - ./src:/app/src
      - ./index.html:/app/index.html

  release:
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      API_BASE_URL: ${VITE_API_BASE_URL}
      PORT: 80
    ports:
      - 80:80