name: Trigger auto deployment for maxfelker

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/maxfelker-AutoDeployTrigger-3aecac79-ab49-4827-835c-779ad01f025c.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MAXFELKER_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: maxfelkershared.azurecr.io
          registryUsername: ${{ secrets.MAXFELKER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MAXFELKER_REGISTRY_PASSWORD }}
          containerAppName: maxfelker
          resourceGroup: maxfelker.com
          imageToBuild: maxfelkershared.azurecr.io/openai-poc:${{ github.sha }}
          
            

     

